### ISSUE TITLE
Incorrect criteria-based kill statistics calculation in commendations

### ISSUE THREAD

**Issue by just-dont** [OpenXcom/OpenXcom#1302]
The part of the statistic-keeping code that deals with these 3 commendation types - killsWithCriteriaCareer, killsWithCriteriaMission, killsWithCriteriaTurn
https://github.com/OpenXcom/OpenXcom/blob/72af50720b3009351d6510bc1ef1066bbcab228a/src/Savegame/SoldierDiary.cpp#L395-L396
These have double-deep criteria lists, detailing specific criteria how a kill should be achieved to count for this commendation. The outer list is treated as OR list (any of the listed criteria blocks must be satisfied to count), the inner list - as AND (all criteria within a block must be satisfied to count). E.g. multiple kills with grenades should be read as "kill 3 enemies within a turn with BT_GRENADE **or** BT_PROXIMITYGRENADE".
```
    criteria:
      killsWithCriteriaTurn: [1, 2, 3, 3, 3, 3, 4, 4, 4, 4]
    killCriteria:
      -
        - [3, ["FACTION_HOSTILE", "STATUS_DEAD", "BT_GRENADE"]]
      -
        - [3, ["FACTION_HOSTILE", "STATUS_DEAD", "BT_PROXIMITYGRENADE"]]

```
However, the code that awards commendations processes each criteria block separately - no information (apart from a general "success" boolean flag) is carried over to the outer loop:
https://github.com/OpenXcom/OpenXcom/blob/72af50720b3009351d6510bc1ef1066bbcab228a/src/Savegame/SoldierDiary.cpp#L405-L416
So in reality the above rules work in a rather convoluted way: first the code processes the 1st block and goes through all soldier kills if there's enough 3-kills with BT_GRENADE to award next level of commendation, and if there isn't - then it processes the 2nd block, goes though all soldier kills again, but this time checking for BT_PROXIMITYGRENADE weapon.

It can be expressed as "best of" calculation rather than "total", and all the applicable texts in Commendations mod suggest that it's a bug - not a single commendation that's using multiple criteria blocks has a description that hints of this "best of" calculation.

PS: https://github.com/OpenXcom/OpenXcom/issues/1287 is another such issue with statistics housekeeping
